<a href="https://colab.research.google.com/github/GermanAlmanza14/Econometria_con_Python/blob/main/CEOSAL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### License: Creative Commons Attribution 4.0 International (CC BY 4.0)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
<br>
© 2025 Germán Almanza ralmanza@uacj.mx

# **Ejemplo 2.3: Salario de los CEO (salary) y Tasa de Retorno de la empresa (reo)**

Analizaremos los ejemplos de Wooldridge, para nuestra fortuna en python existe un paquete que contiene todas las bases de datos del texto de Wooldridge.
Por lo tanto,  necesitamos instalar el
Python package [wooldridge](https://github.com/spring-haru/wooldridge), introduciendo la siguiente instrucción en una celda.

Thaks to Tetsu HARUYAMA avec [spring-haru](https://github.com/spring-haru).

In [ ]:
!pip install wooldridge

Collecting wooldridge
  Downloading wooldridge-0.5.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from wooldridge) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->wooldridge) (1.17.0)
Downloading wooldridge-0.5.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 34.5 MB/s eta 0:00:00
Installing collected packages: wooldridge
Successfully installed wooldridge-0.5.0

In [ ]:
import wooldridge as woo

ceosal1=woo.dataWoo('ceosal1')
ceosal1

,salary,pcsalary,sales,roe,pcroe,ros,indus,finance,consprod,utility,lsalary,lsales
0,1095,20,27595.000000,14.1,106.400002,191,1,0,0,0,6.998509,10.225389
1,1001,32,9958.000000,10.9,-30.600000,13,1,0,0,0,6.908755,9.206132
2,1122,9,6125.899902,23.5,-16.299999,14,1,0,0,0,7.022868,8.720281
3,578,-9,16246.000000,5.9,-25.700001,-21,1,0,0,0,6.359574,9.695602
4,1368,7,21783.199219,13.8,-3.000000,56,1,0,0,0,7.221105,9.988894
...,...,...,...,...,...,...,...,...,...,...,...,...
204,930,10,1509.099976,9.0,20.500000,131,0,0,0,1,6.835185,7.319269
205,525,3,1097.099976,15.5,20.100000,72,0,0,0,1,6.263398,7.000426
206,658,32,4542.600098,12.1,-7.800000,68,0,0,0,1,6.489205,8.421255
207,555,6,2023.000000,13.7,-14.600000,60,0,0,0,1,6.318968,7.612337
208,626,0,1442.500000,14.4,-10.200000,62,0,0,0,1,6.439351,7.274133

In [ ]:
roe=ceosal1['roe']  # ROE : rate of equity / tasa de retorno
roe

0      14.1
1      10.9
2      23.5
3       5.9
4      13.8
       ...
204     9.0
205    15.5
206    12.1
207    13.7
208    14.4
Name: roe, Length: 209, dtype: float64

In [ ]:
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Histograma :
plt.hist(roe,color='cornflowerblue')
plt.ylabel('frecuencia')
plt.xlabel('roe')
plt.title('mi primer histograma en python')
plt.savefig('Histograma1.pdf')
plt.show()

In [ ]:
# estimate kernel density:
kde=sm.nonparametric.KDEUnivariate(roe)
kde.fit()

In [ ]:
plt.plot (kde.support,kde.density, color='black', linewidth=5)
plt.ylabel('densidad')
plt.xlabel('roe')
plt.title('mi primer CDF en python')

plt.savefig('Densidad1.pdf')
plt.show()

In [ ]:
# subfigure b (kernel density with overlayed histogram) :
plt.hist(roe, color='cornflowerblue', density=True)
plt.plot(kde.support,kde.density, color='black', linewidth=2)
plt.ylabel('densidad')
plt.xlabel('roe')
plt.savefig('Density2.pdf')

# **Medidas de tendencia central**

# **numpy: funciones de estadística**
Principales funciones de Estadística Descriptiva incluidas en el modulo ```numpy```

* ```np.mean(x)```          media aritmetica   $\bar X=\tfrac{1}{n}\sum_{i=1}^nx_i$

* ```np.median(x)```        mediana

* ```np.var(x,ddof=1)```    varianza            $s_x^2=\tfrac{1}{n-1}\sum_{i=1}^n(x_i-\bar x)^2$

* ```np.std(x,ddof=1)```           desviación estandar $s_x=\sqrt{s_x^2}$

* ```np.cov(x,y)```         covarianza          $s_{xy}=\tfrac{1}{n-1}\sum_{i=1}^n(x_i-\bar x)(y_i-\bar y)$

* ```np.corrcoef(x,y)```    coef corr Pearson   $r_{xy}=\frac{s_{xy}}{s_x\cdot s_y}$

\begin{equation}
r_{xy}=\sum_{i=1}^n\frac{(x_i-\bar x)(y_i-\bar y)}
{\sqrt{\sum_{i=1}^n(x_i-\bar x)^2}\sqrt{\sum_{i=1}^n(y_i-\bar y)^2}}\end{equation}

<br>
<br>

### **Observación:**
Hemos denotado $S_x^2$ y $S_x$ a la varianza y desviación estandar **muestrales**, respectivamente. En estas fórmulas el denominador es $n-1$ en lugar de $n$, que se utiliza para definir los mismos estadísticos  **poblacionales**

* * ```np.var(x,ddof=0)```    varianza            $\sigma_x^2=\tfrac{1}{n}\sum_{i=1}^n(x_i-\bar x)^2$

* ```np.std(x,ddof=0)```           desviación estandar $\sigma_x=\sqrt{s_x^2}$

Para evitar el sesgo en los estadísticos muestrales es necesario introducir el denominador $n-1$, este término se conoce como [corrección de Bessel](https://en.wikipedia.org/wiki/Bessel%27s_correction). En python es necesario agregar la opción ```ddof=1``` para obtener la varianza y desviación estandar en las funciones como se señala arriba.

In [ ]:
import numpy as np

In [ ]:
roe_prm=np.mean(roe)

print('El promedio de roe es:',f'{roe_prm:.1f}')
roe_prm

El promedio de roe es: 17.2

np.float64(17.18421050521175)

In [ ]:
salario=ceosal1['salary']
#salario

In [ ]:
salario_prm=np.mean(salario)
salario_prm

In [ ]:
salario_min=np.min(salario)
salario_min

In [ ]:
salario_max=np.max(salario)
salario_max

In [ ]:
salario_med=np.median(salario)
salario_med

In [ ]:
#   Desviacion Estandar poblacional
salario_std=np.std(salario)   # ,ddof=1 grados de libertad Sec. 5.4 // 6.1.2.1
salario_std

In [ ]:
#  Desviacion Estandar muestral
salario_std=np.std(salario,ddof=1)   # ,ddof=1
salario_std

In [ ]:
#   Coeficiente de Correlacion
roe_corr=np.corrcoef(roe,salario)[0,1]
roe_corr

In [ ]:
#  Desviacion Estandar poblacional
roe_std=np.std(roe,ddof=1)
roe_std

In [ ]:
roe2=(roe_std)**2
roe2

In [ ]:
#  Varianza de roe
roe_var=np.var(roe,ddof=1)
roe_var

In [ ]:
#  Matrix de Covarianza salario-roe
cov_sr=np.cov(salario,roe)    #[0,1]
cov_sr

In [ ]:
#  Covarianza salario-roe
COV_sr=cov_sr[0,1]
COV_sr

# **Coeficiente de Correlación de Pearson: bondad de ajuste**


Hemos definido el coeficiente de correlación de Pearson como
\begin{equation}
r_{xy}=\frac{\sum_{i=1}^n(x_i-\bar x)(y_i-\bar y)}
{\sqrt{\sum_{i=1}^n(x_i-\bar x)^2}\sqrt{\sum_{i=1}^n(y_i-\bar y)^2}}=\frac{cov(x,y)}{s_x\cdot s_y}.\end{equation}

Por otra parte, recordemos que el producto punto de los vectores $X$ y $Y$ esta definido como
$$X\cdot Y=\|X\|\|Y\|\cos\theta,$$
donde $\theta$ es el ángulo entre los vectores. Recuerde además que **la norma de un vector** esta definida como
$$\|X\|=\sqrt{x_1^2+x_2^2+\dots+x_k^2}.$$
Por lo tanto
$$\cos\theta=\frac{X\cdot Y}{\|X\|\|Y\|}=
\frac{\sum_{i=1}^n(x_i-\bar x)(y_i-\bar y)}
{\sqrt{\sum_{i=1}^n(x_i-\bar x)^2}\sqrt{\sum_{i=1}^n(y_i-\bar y)^2}}=r_{xy},$$
para
$$X=[(x_1-\bar x),(x_2-\bar x),\dots,(x_n-\bar x)]\quad\text{y}\quad
Y=[(y_1-\bar y),(y_2-\bar y),\dots,(y_n-\bar y)].$$

La identidad anterior muestra que el coeficiente de correlación de Pearson determina el coseno del ángulo entre los vectores $X$ y $Y$; esto significa que $-1\leq r_{xy}\leq 1$.

In [ ]:
#   Coef Correlacion de Pearson
CoefCorr_sr=COV_sr/(roe_std*salario_std)
CoefCorr_sr

In [ ]:
np.corrcoef(salario,roe)

# **Modelo de Regresión Lineal Simple (OLS)**
Las Eq. 2.17 y 2.19  (Wooldridge 2010)
Asumimos que el modelo de regresión lineal simple
$$y=\beta_0+\beta_1 x+u$$
explica la variable (observada) $y$. Nos interesa realizar la estimación de los coeficientes $\beta_0$ y $\beta_1$.

La línea de la regresión OLS esta definida por los estimadores
$$\hat y=\hat\beta_0+\hat\beta_1 x,$$
donde los estimadores estan definidos por
\begin{align}
\hat\beta_0&=\bar y-\beta_1\bar x\\
\hat\beta_1&=\frac{\sum_{i=1}^nx_i(y_i-\bar y)}{\sum_{i=1}^nx_i(x_i-\bar x)}\\
\end{align}

Observe que [**TAREA: demostrar la siguiente identidad**]
$$\begin{align}
\frac{\sum_{i=1}^nx_i(y_i-\bar y)}{\sum_{i=1}^nx_i(x_i-\bar x)}
&=\frac{\sum_{i=1}^n(x_i-\bar x)(y_i-\bar y)}{\sum_{i=1}^n(x_i-\bar x)^2}\\
&=\frac{cov(x,y)}{var(x)}\\
\end{align}$$
por lo tanto

\begin{align}
\hat\beta_0&=\bar y-\beta_1\bar x\\
\hat\beta_1&=\frac{cov(x,y)}{var(x)}\\
\end{align}

In [ ]:
Beta1=COV_sr/roe_var
Beta1

In [ ]:
Beta0=salario_prm-Beta1*roe_prm
Beta0

Con los valores de los estadísticos anteriores, tenemos la **ecuación de regresión lineal**
$$\widehat{salario}=963.1913+18.5011*roe$$

In [ ]:
#   Coef Correlacion de Pearson
CoefCorr_sr=COV_sr/(roe_std*salario_std)
CoefCorr_sr

In [ ]:
CoefCorr_sr**2

In [ ]:
from scipy import stats

# Calculate Pearson correlation
pearson_corr, _ = stats.pearsonr(roe, salario)
print(f"Pearson correlation: {pearson_corr}")

# **OLS con funciones de python**

In [ ]:
import wooldridge as woo
import numpy as np
import statsmodels.formula.api as stf

ceosal1=woo.dataWoo('ceosal1')
# regresion OLS:  stf.ols('Y~X',data=name)
reg1=stf.ols('salary ~ roe',data=ceosal1).fit()

In [ ]:
# Muestra la estadistica or resumen de la regresion
reg1.summary()

## **Observemos que el t-value se calcula así:**

$$t-value=\frac{\hat\beta_i}{std.err(\hat\beta_i)}$$

In [ ]:
963.1913/213.240

In [ ]:
BETA=reg1.params
BETA

In [ ]:
beta0=BETA[0]
beta1=BETA[1]

In [ ]:
reg1.t_test([[1,0],[0,1]])

El $p$-value de $\beta_1$ (c1)  $p=0.098>0.05$ muestra que el coeficiente $\beta_1$ no es estadisticamente significativo. Por tanto, la relación no es representativa.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
#   Grafica los 'puntos' que definen las variables
plt.plot('roe','salary',data=ceosal1,color='g',marker='+',linestyle='',label='roe')
#   Grafica la 'recta de ajuste'
plt.plot(ceosal1['roe'],reg1.fittedvalues,color='red',linestyle='-',label='linea de ajuste')
plt.ylabel ('salario')
plt.xlabel ('roe')
#   titulo
plt.title(r'$\widehat Y$ ='f'{beta0:.3f}+{beta1:.3f}x', size=12)
plt.legend()
plt.savefig('Regresion1.jpg')
plt.show()

# Función de 'pronostico' de la regresión

In [ ]:
def Y(x):
    return beta0+beta1*x

Y(20)

Queremos realizar un pronostico para una lista de valores.

Comenzamos por definir los valores a evaluar con un array.

In [ ]:
valores=np.array([10, 20, 30, 40, 50])
pronostico=np.array([Y(val) for val in valores])
pronostico

In [ ]:
plt.figure(figsize=(10,6))

plt.plot('roe','salary',data=ceosal1,color='g',marker='o',linestyle='',label='roe')
plt.plot(ceosal1['roe'],reg1.fittedvalues,color='red',linestyle='-',label='regresión')
plt.plot(valores,pronostico,color='b',marker='*',linestyle='',label='pronostico',  markersize=10)

plt.ylabel ('salario')
plt.xlabel ('roe')
#   titulo
plt.title(f'$\widehat y$ ='+'{:.3f}'.format(Beta0)+ '+{:.3f}'.format(Beta1)+' x', size=12)
plt.legend()
plt.savefig('Regresion2b.jpg')
plt.show()

# Residuales

Recordemos que la predicción de los valores de $y$ estan dados por la ecuación
$$\hat y_i=\hat\beta_0+\hat\beta_1 x_i,$$
los residuales de cada observación estan definidos por
$$\hat u_i=y_i-\hat y_i.$$
Enseguida definimos los residuales para la regresión 'salario~roe'

In [ ]:
# En terminos generales, llamamos la variable 'x' del Data_Base DT
#y_Hat=Beta0+Beta1*ceosal1['roe']

#  Como ya hemos definido roe=ceosal1['roe']
Hat_y=Beta0+Beta1*roe
#Hat_y
Hat_U=salario-Hat_y
Hat_U

In [ ]:
# calcula la estimacion de la regresion para 'y(salario)' y los residuales:
hat_sal=reg1.fittedvalues
#hat_sal
hat_u=reg1.resid
hat_u

# Tabla de Residuos
Las primeras dos variable 'y_Hat' y 'U_Hat' las obtuvimos aritmeticamente. Sin embargo, python las calcula con las funciones '.fittedvalues' y '.resid'

Para comparar estos valores, creamos una tabla con el modulo 'pandas'

In [ ]:
import pandas as pd

tabla2=pd.DataFrame({'hat_sal=reg1.fittedvalues':hat_sal,
                     'Hat_Y=Beta0+Beta1*roe':Hat_y,
                   'Hat_U=salario-Hat_y':Hat_U,
                   'hat_u=reg1.resid':hat_u})
tabla2

# .head(n); donde 'n' es el numero de renglones que visualiza/muestra
#T_PR.head(20)

In [ ]:
sum(hat_u**2)

In [ ]:
#  Tabla 2.2 de Wooldridge
TW_2p2=pd.DataFrame({'roe': ceosal1['roe'],
                     'salario': ceosal1['salary'],
                     'hat_sal':hat_sal,
                     'hat_u':hat_u})
TW_2p2.head(15)

# Propiedades algebraicas de los estimadores de OLS

* Suma de los residuos es cero.
$$\hat u_i=y_i-(\hat\beta_0+\hat\beta_1 x_i) \qquad\sum_{i=1}^n\hat u_i=0
  \quad\Rightarrow\quad \overline{\hat u_i}=0.$$

* La covarianza muestral entre regresores y residuales es cero
$$\sum_{i=1}^nx_i\hat u_i=0\quad\Rightarrow\quad Cov(x_i,\hat u_i)=0$$

* El punto $(\bar x,\bar y)$ esta en la recta de regresión

  $$\bar y=\hat\beta_0+\hat\beta_1 \bar x.$$

In [ ]:
Shat_u=np.sum(hat_u)
Shat_u

In [ ]:
Sres=np.sum(salario-hat_sal)
Sres

In [ ]:
#sum_rss="{:.4f}".format(res)
#sum_rss='%0.4f'%res
#sum_rss=f'res:0.4f'
sum_rss=f'{res:.4f}'
#sum_rss=round(Sres,2)
sum_rss

In [ ]:
np.mean(hat_u)
#round(np.mean(hat_u),2)

In [ ]:
np.cov(roe,hat_u)[0,1]

# STC=SEC+SRC
* Suma total de cuadrados: mide la dispersión de los $y_i$
  $$STC=\sum_{i=1}^n(y_i-\bar y)^2=(n-1)Var(y).$$
* Suma explicada de cuadrados: mide la variación muestral de las $\hat y_i$
  $$SEC=\sum_{i=1}^n(\hat y_i-\bar y)^2=(n-1)Var(\hat y).$$
* Suma residual de cuadrados: mide la variación muestral de los residuales
  $$SRC=\sum_{i=1}^n\hat u_i^2=(n-1)Var(\hat u).$$

In [ ]:
# calculate R'2 in three different ways:
sal=ceosal1['salary']
R2_a=np.var(hat_sal, ddof=1)/np.var(sal,ddof=1)
R2_b=1-np.var(hat_u, ddof=1)/np.var(sal,ddof=1)
R2_c=np.corrcoef(sal,hat_sal)[1, 0]** 2

In [ ]:
R2_a

In [ ]:
R2_b

In [ ]:
R2_c

In [ ]:
CoefCorr_sr**2

#